// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW4CHv4I4m0VJOU3pPS_ctSoBulcaF1T0',
    appId: '1:686935416456:web:f9cd76ad2d11b2e60cc93d',
    messagingSenderId: '686935416456',
    projectId: 'fir-app-3f476',
    authDomain: 'fir-app-3f476.firebaseapp.com',
    storageBucket: 'fir-app-3f476.firebasestorage.app',
    measurementId: 'G-X8JEX5MZZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVtA1igfDsIA9I-_uA37DwMJP4mt_3Dwo',
    appId: '1:686935416456:android:bc6e6e17b8b902890cc93d',
    messagingSenderId: '686935416456',
    projectId: 'fir-app-3f476',
    storageBucket: 'fir-app-3f476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHpdTvtkF5Eq6szi2q4_S4gFG6gTc7e5c',
    appId: '1:686935416456:ios:b6ffc8ccc15e18be0cc93d',
    messagingSenderId: '686935416456',
    projectId: 'fir-app-3f476',
    storageBucket: 'fir-app-3f476.firebasestorage.app',
    iosBundleId: 'com.example.btlAndroidNc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHpdTvtkF5Eq6szi2q4_S4gFG6gTc7e5c',
    appId: '1:686935416456:ios:b6ffc8ccc15e18be0cc93d',
    messagingSenderId: '686935416456',
    projectId: 'fir-app-3f476',
    storageBucket: 'fir-app-3f476.firebasestorage.app',
    iosBundleId: 'com.example.btlAndroidNc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW4CHv4I4m0VJOU3pPS_ctSoBulcaF1T0',
    appId: '1:686935416456:web:05771ce1e8cd74540cc93d',
    messagingSenderId: '686935416456',
    projectId: 'fir-app-3f476',
    authDomain: 'fir-app-3f476.firebaseapp.com',
    storageBucket: 'fir-app-3f476.firebasestorage.app',
    measurementId: 'G-EKLJSDGE81',
  );
}
